name: manual_msi_build
on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        shell: bash
        run: |
          matrix='{"include":[]}'
          if [ "${{ inputs.build_amd64 }}" = "true" ]; then
            matrix=$(echo $matrix | jq -c '.include += [{"arch":"amd64","msi_name":"observiq-otel-collector.msi","msi_arch":"x64"}]')
          fi
          if [ "${{ inputs.build_arm64 }}" = "true" ]; then
            matrix=$(echo $matrix | jq -c '.include += [{"arch":"arm64","msi_name":"observiq-otel-collector-arm64.msi","msi_arch":"arm64"}]')
          fi
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  build-msi:
    needs: setup
    runs-on: windows-2022
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: internal/extension/opampconnectionextension/go.mod
      - name: Install ocb
        run: make install-ocb
        shell: bash
      - name: Prepare Release Dependencies
        run: make release-prep CURR_VERSION=${VERSION#v}
        shell: bash
        env:
          VERSION: ${{ github.event.inputs.version }}
      - name: Build Windows Binaries
        run: make build-windows-${{ matrix.arch }}
      - name: Copy Shared Files to MSI Build Directory
        run: |
          cp -r release_deps/plugins windows/
          cp config/example.yaml windows/config.yaml
          cp config/logging.yaml windows/logging.yaml
          cp LICENSE windows/LICENSE
          cp release_deps/VERSION.txt windows/VERSION.txt
      - name: Copy Binaries
        run: |
          cp dist/collector_windows_${{ matrix.arch }}.exe windows/observiq-otel-collector.exe
          cp dist/updater_windows_${{ matrix.arch }}.exe windows/updater.exe
      # HACK: Copy build directory to C drive to avoid this error, since there must be a relative path from the tempdir that go-msi uses
      # for the MSI to build properly
      - name: Copy Build Dir
        run: |
          cp -r windows C:/build
          echo "C:/build" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      # Installs go-msi and wix.
      - name: Install Build Tools
        run: |
          curl -f -L -o go-msi.exe https://github.com/observIQ/go-msi/releases/download/v2.2.0/go-msi.exe
          curl -f -L -o wix314-binaries.zip https://github.com/wixtoolset/wix3/releases/download/wix314rtm/wix314-binaries.zip
          unzip wix314-binaries.zip
        working-directory: C:/build
      - name: Build MSI
        run: go-msi.exe make -m ${{ matrix.msi_name }} --version ${{ github.event.inputs.version }} --arch ${{ matrix.msi_arch }}
        working-directory: C:/build
      - name: Install DigiCert Client tools from Github Custom Actions marketplace
        uses: digicert/ssm-code-signing@v1.0.0
      - name: Set up certificate
        run: |
          echo "${{ secrets.SM_CLIENT_CERT_FILE_B64 }}" | base64 --decode > /d/Certificate_pkcs12.p12
        shell: bash
      - name: Set variables for signing
        id: variables
        run: |
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          echo "SM_HOST=${{ secrets.SM_HOST }}" >> "$GITHUB_ENV"
          echo "SM_API_KEY=${{ secrets.SM_API_KEY }}" >> "$GITHUB_ENV"
          echo "SM_CLIENT_CERT_FILE=D:\\Certificate_pkcs12.p12" >> "$GITHUB_ENV"
          echo "SM_CLIENT_CERT_PASSWORD=${{ secrets.SM_CLIENT_CERT_PASSWORD }}" >> "$GITHUB_ENV"
        shell: bash
      - name: Sign MSI
        run: |
          smctl sign --keypair-alias ${{ secrets.BDOT_DIGICERT_KEYPAIR_ALIAS }} --input C:/build/${{ matrix.msi_name }} --config-file C:\Users\RUNNER~1\AppData\Local\Temp\smtools-windows-x64\pkcs11properties.cfg
        shell: cmd
      - name: Upload MSI
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.msi_name }}
          path: C:/build/${{ matrix.msi_name }}
          # Short lived because this is meant as an action for developers
          retention-days: 1
