name: Release Test
on:
  workflow_dispatch:

jobs:
  build-msi:
    runs-on: windows-2022
    strategy:
      matrix:
        include:
          - arch: amd64
            msi_name: observiq-otel-collector.msi
            msi_arch: x64
          - arch: arm64
            msi_name: observiq-otel-collector-arm64.msi
            msi_arch: arm64
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: internal/extension/opampconnectionextension/go.mod
      - name: Install ocb
        run: make install-ocb
        shell: bash
      - name: Prepare Release Dependencies
        run: make release-prep CURR_VERSION=${VERSION#v}
        shell: bash
        env:
          VERSION: ${{ github.event.inputs.version }}
      - name: Build Windows Binaries
        run: make build-windows-${{ matrix.arch }}
      - name: Copy Shared Files to MSI Build Directory
        run: |
          cp -r release_deps/plugins windows/
          cp config/example.yaml windows/config.yaml
          cp config/logging.yaml windows/logging.yaml
          cp LICENSE windows/LICENSE
          cp release_deps/VERSION.txt windows/VERSION.txt
      - name: Copy Binaries
        run: |
          cp dist/collector_windows_${{ matrix.arch }}.exe windows/observiq-otel-collector.exe
          cp dist/updater_windows_${{ matrix.arch }}.exe windows/updater.exe
      # HACK: Copy build directory to C drive to avoid this error, since there must be a relative path from the tempdir that go-msi uses
      # for the MSI to build properly
      - name: Copy Build Dir
        run: |
          cp -r windows C:/build
          echo "C:/build" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      # Installs go-msi and wix.
      - name: Install Build Tools
        run: |
          curl -f -L -o go-msi.exe https://github.com/observIQ/go-msi/releases/download/v2.2.0/go-msi.exe
          curl -f -L -o wix314-binaries.zip https://github.com/wixtoolset/wix3/releases/download/wix314rtm/wix314-binaries.zip
          unzip wix314-binaries.zip
        working-directory: C:/build
      - name: Build MSI
        run: go-msi.exe make -m ${{ matrix.msi_name }} --version ${{ github.event.inputs.version }} --arch ${{ matrix.msi_arch }}
        working-directory: C:/build
      - name: Install DigiCert Client tools from Github Custom Actions marketplace
        uses: digicert/ssm-code-signing@v1.0.0
      - name: Set up certificate
        run: |
          echo "${{ secrets.SM_CLIENT_CERT_FILE_B64 }}" | base64 --decode > /d/Certificate_pkcs12.p12
        shell: bash
      - name: Set variables for signing
        id: variables
        run: |
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          echo "SM_HOST=${{ secrets.SM_HOST }}" >> "$GITHUB_ENV"
          echo "SM_API_KEY=${{ secrets.SM_API_KEY }}" >> "$GITHUB_ENV"
          echo "SM_CLIENT_CERT_FILE=D:\\Certificate_pkcs12.p12" >> "$GITHUB_ENV"
          echo "SM_CLIENT_CERT_PASSWORD=${{ secrets.SM_CLIENT_CERT_PASSWORD }}" >> "$GITHUB_ENV"
        shell: bash
      - name: Sign MSI
        run: |
          smctl sign --keypair-alias ${{ secrets.BDOT_DIGICERT_KEYPAIR_ALIAS }} --input C:/build/${{ matrix.msi_name }} --config-file C:\Users\RUNNER~1\AppData\Local\Temp\smtools-windows-x64\pkcs11properties.cfg
        shell: cmd
      - name: Upload MSI
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.msi_name }}
          path: C:/build/${{ matrix.msi_name }}
          retention-days: 1

  release-test:
    runs-on: namespace-profile-bindplane-default-ubuntu-24-04-32x128
    needs: [build-msi]
    steps:
      - name: Checkout Repo
        uses: namespacelabs/nscloud-checkout-action@v7
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: internal/extension/opampconnectionextension/go.mod
          cache: false # Use Namespace caching instead
      - name: Set up Go cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: go
      - name: Install ocb
        run: make install-ocb

      - name: Retrieve Windows AMD64 MSI Installer
        uses: actions/download-artifact@v4
        with:
          name: observiq-otel-collector.msi

      - name: Retrieve Windows ARM64 MSI Installer
        uses: actions/download-artifact@v4
        with:
          name: observiq-otel-collector-arm64.msi

      - name: Install cosign
        run: go install github.com/sigstore/cosign/cmd/cosign@v1.13.1
      - name: Build cosign key file
        run: 'echo "$COSIGN_PRIVATE_KEY" >> cosign.key'
        shell: bash
        env:
          COSIGN_PRIVATE_KEY: ${{secrets.ORG_COSIGN_PRIVATE_KEY}}

      - name: Sign AMD64 MSI
        run: cosign sign-blob --key=cosign.key --output-signature ./observiq-otel-collector.msi.sig ./observiq-otel-collector.msi
        shell: bash
        env:
          COSIGN_PASSWORD: ${{ secrets.ORG_COSIGN_PWD }}

      - name: Sign ARM64 MSI
        run: cosign sign-blob --key=cosign.key --output-signature ./observiq-otel-collector-arm64.msi.sig ./observiq-otel-collector-arm64.msi
        shell: bash
        env:
          COSIGN_PASSWORD: ${{ secrets.ORG_COSIGN_PWD }}

      - name: Set VERSION
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Cache Goreleaser Build
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: ~/.cache/goreleaser

      - name: Write signing key for nFPM
        shell: bash
        run: |
          cat > ci-signing-key.asc <<'EOF'
          ${{ secrets.GPG_PRIVATE_SIGNING_KEY }}
          EOF
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          version: "v2.12.5"
          args: release --skip=publish --skip=validate --clean
        env:
          GORELEASER_CURRENT_TAG: ${{ env.VERSION }}
          GITHUB_TOKEN: ${{ secrets.ORG_GORELEASER_GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          SIGNING_KEY_FILE: ci-signing-key.asc
          COSIGN_PWD: ${{ secrets.ORG_COSIGN_PWD }}

      - name: Debug list dist/
        run: |
          ls -laR dist/

      - name: Create artifact archive
        run: |
          mkdir artifacts
          cp ./scripts/install/*.sh ./artifacts
          cp ./scripts/install/*.ps1 ./artifacts
          cp ./release_deps/gpg-keys.tar.gz ./artifacts/gpg-keys.tar.gz
          cp ./observiq-otel-collector.msi ./artifacts
          cp ./observiq-otel-collector-arm64.msi ./artifacts
          cp ./dist/*tar.gz ./artifacts
          cp ./dist/*.zip ./artifacts
          cp ./dist/*.rpm ./artifacts
          cp ./dist/*.deb ./artifacts
          cp ./dist/*SHA256SUMS ./artifacts
          tar -czvf observiq-otel-collector-${{ github.event.inputs.version }}-artifacts.tar.gz -C ./artifacts .

      - name: Sign artifact archive
        run: cosign sign-blob --key=cosign.key --output-signature ./observiq-otel-collector-${{ github.event.inputs.version }}-artifacts.tar.gz.sig ./observiq-otel-collector-${{ github.event.inputs.version }}-artifacts.tar.gz
        shell: bash
        env:
          COSIGN_PASSWORD: ${{ secrets.ORG_COSIGN_PWD }}

      - name: Check Artifacts Directory
        run: |
          ls -la artifacts
          du -sh artifacts

      - name: Upload build artifacts
        uses: namespace-actions/upload-artifact@v1
        with:
          name: observiq-otel-collector-${{ github.event.inputs.version }}-artifacts.tar.gz
          path: observiq-otel-collector-${{ github.event.inputs.version }}-artifacts.tar.gz
          retention-days: 1

      # Linux package uploads to Google Artifact Registry

      # google-github-actions/auth@v2 was used above to install
      # gcloud sdk. google-github-actions/auth was used as well
      # but we need to re-authenticate to upload packages to the
      # correct project.
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.ORG_BINDPLANE_PUBLIC_LINUX_REPO_JSON_KEY }}"

      - name: Upload Bindplane Linux AMD64 Deb Package
        run: |
          gcloud \
            --project bindplane-repository \
            artifacts apt upload devel-deb \
            --location us-central1 \
            --source dist/observiq-otel-collector_${{ env.VERSION }}_linux_amd64.deb

      - name: Upload Bindplane Linux AMD64 RPM Package
        run: |
          gcloud \
            --project bindplane-repository \
            artifacts yum upload devel-rpm \
            --location us-central1 \
            --source dist/observiq-otel-collector_${{ env.VERSION }}_linux_amd64.rpm

      - name: Upload Bindplane Linux ARM64 Deb Package
        run: |
          gcloud \
            --project bindplane-repository \
            artifacts apt upload devel-deb \
            --location us-central1 \
            --source dist/observiq-otel-collector_${{ env.VERSION }}_linux_arm64.deb

      - name: Upload Bindplane Linux ARM64 RPM Package
        run: |
          gcloud \
            --project bindplane-repository \
            artifacts yum upload devel-rpm \
            --location us-central1 \
            --source dist/observiq-otel-collector_${{ env.VERSION }}_linux_arm64.rpm

      - name: Upload Bindplane Linux ARM32 Deb Package
        run: |
          gcloud \
            --project bindplane-repository \
            artifacts apt upload devel-deb \
            --location us-central1 \
            --source dist/observiq-otel-collector_${{ env.VERSION }}_linux_arm.deb

      - name: Upload Bindplane Linux ARM32 RPM Package
        run: |
          gcloud \
            --project bindplane-repository \
            artifacts yum upload devel-rpm \
            --location us-central1 \
            --source dist/observiq-otel-collector_${{ env.VERSION }}_linux_arm.rpm

      - name: Upload Bindplane Linux PPC64LE Deb Package
        run: |
          gcloud \
            --project bindplane-repository \
            artifacts apt upload devel-deb \
            --location us-central1 \
            --source dist/observiq-otel-collector_${{ env.VERSION }}_linux_ppc64le.deb

      - name: Upload Bindplane Linux PPC64LE RPM Package
        run: |
          gcloud \
            --project bindplane-repository \
            artifacts yum upload devel-rpm \
            --location us-central1 \
            --source dist/observiq-otel-collector_${{ env.VERSION }}_linux_ppc64le.rpm

      - name: Upload Bindplane Linux PPC64 Deb Package
        run: |
          gcloud \
            --project bindplane-repository \
            artifacts apt upload devel-deb \
            --location us-central1 \
            --source dist/observiq-otel-collector_${{ env.VERSION }}_linux_ppc64.deb

      - name: Upload Bindplane Linux PPC64 RPM Package
        run: |
          gcloud \
            --project bindplane-repository \
            artifacts yum upload devel-rpm \
            --location us-central1 \
            --source dist/observiq-otel-collector_${{ env.VERSION }}_linux_ppc64.rpm
